### ISSUE TITLE
Error install iOS platform / Error: pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by addodelgrossi** [chemerisuk/cordova-plugin-firebase-analytics#103]
` cordova plugin add cordova-plugin-firebase-analytics --save
`, fails on ios

cordova-> 8.1.2 (cordova-lib@8.1.1)
cocoapods -> 1.6.1 

And the `pod repo update` updated.

Any ideas how to fix it?

```
 cordova plugin add cordova-plugin-firebase-analytics --save
Installing "cordova-plugin-firebase-analytics" for android
Plugin dependency "cordova-support-android-plugin@1.0.1" already fetched, using that version.
Installing "cordova-support-android-plugin" for android
Android Studio project detected
Plugin dependency "cordova-support-google-services@1.3.1" already fetched, using that version.
Dependent plugin "cordova-support-google-services" already installed on android.
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-firebase-analytics" for ios
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/addo/jobs/personal/pushpromo/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:188:13)
    at Pipe._handle.close (net.js:610:12)
pod: Command failed with exit code 1

```

**Comment by addodelgrossi** [comment]
I have revalidated all settings. I also tried in an earlier version and continue with the same error.

Any idea ?

**Comment by geshub** [comment]
I'm stuck with the same error on IOS

**Comment by saberprashant** [comment]
Hi @addodelgrossi @geshub , to solve this error, you actually have to setup pod in your project, simply run:
`pod setup` or `pod init` as per your configuration.

Now, with this, firebase-analytics was successfully installed in my project and it build perfectly as well with `ionic cordova build ios`, but when I do the final build on Xcode, it is failing (due to some linker issues). Please do the `pod setup` and tell me, if all goes right for you or not(mainly when you build it in Xcode).

Thanks! :)

**Comment by geshub** [comment]
@saberprashant thanks for your help. 
I did succeed with the install and the IOS build.
In my case I had several cocoapods versions installed on my Mac.

**Comment by saberprashant** [comment]
@geshub , can you please tell me what version of pod you used to build the project on Xcode.
Or, it would be better if you could tell me all the steps.

Because, in my case, my `ionic cordoba build ios` working perfectly, but after that, when I open the `.xcworkspace` file, it is giving me this error:
`
ld: 175 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

and I still didn't get a way to resolve this.
Please help.

**Comment by xinfengmich** [comment]
I have similar error on iOS as following: 
$ cordova plugin add cordova-plugin-firebase-analytics --variable FIREBASE_CORE_VERSION=15.0.1
Installing "cordova-plugin-firebase-analytics" for android
Plugin dependency "cordova-support-android-plugin@1.0.1" already fetched, using that version.
Installing "cordova-support-android-plugin" for android
Plugin dependency "cordova-support-google-services@1.2.1" already fetched, using that version.
Dependent plugin "cordova-support-google-services" already installed on android.
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-firebase-analytics" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/xinfeng/Documents/gitRepo/michigan-mobile/node_modules/cordova-common/src/superspawn.js:125:23)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
pod: Command failed with exit code 1

Seems conflict with phonegap-plugin-push.   Once I removed phonegap-plugin-push,  cordova-plugin-firebase-analytics is installed fine.  Can cordova-plugin-firebase-analytics coexist with phonegap-plugin-push ?

**Comment by saberprashant** [comment]
Hi @xinfengmich , well, I was unable to make the `cordova-plugin-fcm` work with this plugin. It seems to me that your problem might be similar as you are using `phonegap-plugin-push`.
But still, you can give it a try.
To remove this pod error, go to `/platforms/ios` and do:
`pod install`

After this. all the dependencies will get installed, and then run:
`ionic cordova build ios`

Then, go to Xcode, and remove these frameworks from `Libraries and Frameworks`:
- Firebase Core (Do check first, if it is present in the `PODS` project)
- Firebase instance id (Do check first, if it is present in the `PODS` project)
- Remove all frameworks which are the same as the ones present in `PODS` project.

After this, try to build your app. 😄 

In my case, this worked out, but the push notifications were stopped on iOS (on Android, it is working flawlessly).

Thanks! 😄

**Comment by xinfengmich** [comment]
@saberprashant  Thanks for your information. 
I had to usecordova-plugin-firebase-analytics@0.12.0 instead due to the firebase version conflict within phonegap-plugin-push@2.2.3.

$ cordova plugin add cordova-plugin-firebase-analytics@0.12.0 --variable FIREBASE_CORE_VERSION=12.0.1 --force

For Push Notification on iOS, since we still use use apns, so I followed https://github.com/phonegap/phonegap-plugin-push/issues/2112 to change the value of the key IS_GCM_ENABLED to false in GoogleService-Info.plist.   Then Push Notification worked on both iOS and Android.

**Comment by saberprashant** [comment]
Hi @xinfengmich , that's great ya. I'll try the same 😄 🍻

**Comment by ardabeyazoglu** [comment]
I solved it as i mentioned before [here](https://github.com/phonegap/phonegap-plugin-push/issues/2112#issuecomment-463971522) 

> I had recently this issue. The only solution worked for me is this:
> + Remove both plugins, remove platform ios
> + cordova plugin add phonegap-plugin-push@2.1.3 --save
> + Clone the cordova-plugin-firebase-analytics repo, modify plugin.xml and set firebase/core podspec to 4.0.0
> + cordova plugin add {forked-repo-url}.git
> + pod install (in ios folder)
> + Now both works normally.

**Comment by Ross-Rawlins** [comment]
is this the correct fix for this?

**Comment by 814k31** [comment]
Possibly related:

If i have cordova-plugin-firebase-crashlytics installed before cordova-plugin-firebase-analytics

I get a pod install error

however if I have them the other way round it installs fine

Broken on master
https://github.com/814k31/cordova-firebase-pod-error

Fixed on swap plugin order
https://github.com/814k31/cordova-firebase-pod-error/tree/swap-plugin-order

**Comment by bijanmmarkes** [comment]
`pod repo update` fixed this type of issue for me.

**Comment by kenibarwick** [comment]
> `pod repo update` fixed this type of issue for me.

this also worked in my case
