### ISSUE TITLE
failed to install: cordova platform add on mac os catalina 

### ISSUE THREAD

**Issue by steppe87** [chemerisuk/cordova-plugin-firebase-analytics#146]
After upgrading mac os to "catalina", i am getting errors while doing "cordova platform add ios":

here is the logging:
```
...
Installing "cordova-plugin-firebase-analytics" for ios
Failed to install 'cordova-plugin-firebase-analytics': undefined
Failed to restore plugin "cordova-plugin-firebase-analytics" from config.xml. You might need to try adding it again. Error: /bin/sh: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory
...
```

the default ruby version of catalina is 2.6.
So the cordova plugin anyhow tries to reach the old ruby version 2.3

How can i fix this. 
Or do we need a patching version of "cordova-plugin-firebase-analytics"?

**Comment by nuryagdym** [comment]
In my case the following commands solved my issue:
1. `gem install cocoapods`
if you permission errors while running this
added following lines to ~/.profile 
`export GEM_HOME=~/.gem
export PATH="$GEM_HOME/bin:$PATH"`
(Catalina by default uses zsh shell so you might need to add this files to ~/.zprofile or you can default shell to use bash)

2. I also run this command but I am not sure you need to run it or not, because I don't know what it does:
`pod setup`

3. Delete platform and plugins folder from your project and try to add IOS platform again

Hope this will help you also
