### ISSUE TITLE
Cannot add extension with name googleServices

### ISSUE THREAD

**Issue by gazzaf** [chemerisuk/cordova-plugin-firebase-analytics#191]
I tried to install for Android only to begin with...

```
Plugin doesn't support this project's cordova-android version. cordova-android: 9.1.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android
```

Anyway, I tried to build the project and it failed with this...

```
Adding classpath: com.google.gms:google-services:4.3.3
FAILURE: Build failed with an exception.
 Where:
Build file 'D:\App\platforms\android\app\build.gradle' line: 434
 What went wrong:
A problem occurred evaluating project ':app'.
 Failed to apply plugin [id 'com.google.gms.google-services']
    Cannot add extension with name 'googleServices', as there is an extension already registered with that name.
```

`cordova plugins list`
- cordova-open-native-settings 1.5.3 "Native settings"
- cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
- cordova-plugin-device 2.0.3 "Device"
- cordova-plugin-firebase-analytics 5.0.0 "FirebaseAnalyticsPlugin"
- cordova-plugin-geolocation 4.1.0 "Geolocation"
- cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
- cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
- cordova-plugin-network-information 2.0.2 "Network Information"
- cordova-plugin-web-share 1.2.0 "WebShare"
- cordova-plugin-whitelist 1.3.4 "Whitelist"
- cordova-support-android-plugin 1.0.2 "cordova-support-android-plugin"
- cordova-support-google-services 1.4.1 "cordova-support-google-services"
- cordova.plugins.diagnostic 6.0.3 "Diagnostic"
- pushwoosh-cordova-plugin 8.1.1 "Pushwoosh"
- pushwoosh-geozones-cordova-plugin 1.17.0 "PushwooshGeozones"

Thanks in advance for any tips.
Gary

**Comment by simonwatt** [comment]
@gazzaf I'm having the exact same error. I'm also using pushwoosh-cordova-plugin so I think that is likely the clashing plugin. Did you end up finding a fix?

I'm only trying this plugin instead of cordova-plugin-firebasex since the FCM on there was causing the Pushwoosh plugin not to work...

**Comment by gazzaf** [comment]
@simonwatt Unfortunately I'm not smart enough to find a fix, so I've used web-based Google Analytics like the good old days. The app sends some URL params (page name and any custom dimensions) to a static page on my web server (which can also be hosted on a CDN), and some js in the static page simply takes those URL params and sends them as gtag events to GA. This works very nicely but only for Android. After days of debugging it turns out that GA blocks requests coming from Cordova apps in iOS because the host domain starts with app:// which is a pain in the rear end. GA does not let me whitelist app:// as part of a permitted domain. :-(

So my app metrics are based purely on Android users which accounts for 40% of all users, so I'm just multiplying the GA stats by 1.6 to estimate the total number of hits that any screen within the app gets. It's not perfect but it's better than nothing. I would prefer to use a Firebase GA plugin as a solution - ideally one with some documentation. 🙊

**Comment by simonwatt** [comment]
@gazzaf I gave up on trying to use this plugin due to the above error, but I suspect the issue was to do with it and the pushwoosh-cordova-plugin using different versions of firebase dependencies. The ANDROID_FIREBASE_ANALYTICS_VERSION 
 of this plugin is configurable as per the documentation, but I tried a few values with no success so it might be a different firebase dependency causing the issue. 

The solution might be forking one of the two, and making sure all firebase dependencies are in line with each other. Note - when I removed the pushwoosh plugin to check it was the clashing plugin I no longer got an error which is why I'm sure that is the clashing plugin.

I ended up using cordova-plugin-firebasex for the analytics instead, the problem is that plugin also includes a bunch of other stuff not just analytics. In my case the Push Notification receivers from cordova-plugin-firebasex were clashing with PushWoosh causing the PushWoosh notifications to stop being received so I ended up removing PushWoosh from my project, and just using the FCM push notifications from cordova-plugin-firebasex instead... Not sure if that's an option for you as I don't know what you use pushwoosh for; in my case I was just sending notifications from the dashboard so the firebase dashboard offered the same.

**Comment by gazzaf** [comment]
@simonwatt Thank you for sharing details of what you found out. I'm tied to Pushwoosh because of its geozone functionality so I wouldn't be able to ditch it an use the firebaseX plugin. I don't know if the author of cordova-plugin-firebase-analytics would fix it to play nicely with Pushwoosh and its version of firebase dependencies, but I imagine not if he doesn't use it for his projects.

**Comment by chemerisuk** [comment]
Latest release doesn’t depend on cordova-support-google-services.
